-- Seed migrations (V1_1, V1_6) insert explicit id values. GENERATED BY DEFAULT AS
-- IDENTITY sequences don't advance for explicit inserts, so the first row created
-- through the app after seeding collides with a seeded id. Resync every sequence
-- that received explicit-id seed data.
SELECT setval('users_id_seq', (SELECT COALESCE(MAX(id), 1) FROM users));
SELECT setval('categories_id_seq', (SELECT COALESCE(MAX(id), 1) FROM categories));
SELECT setval('products_id_seq', (SELECT COALESCE(MAX(id), 1) FROM products));
SELECT setval('product_images_id_seq', (SELECT COALESCE(MAX(id), 1) FROM product_images));
SELECT setval('product_variations_id_seq', (SELECT COALESCE(MAX(id), 1) FROM product_variations));
